### ISSUE TITLE
icerik gondermek isteyenler icin form veya mail adresi baglantisi

### ISSUE THREAD

**Issue by coskung** [chrishoca/chrishoca.github.com#2]
insanlara icerik saglayin diyoruz, sayfaya geldiklerinde nasil icerik gondereceklerine dair bir link vb lazim

**Comment by csenol** [comment]
Pull request acsinlar. Chrisi taniyanlar zaten ITcidir

**Comment by coskung** [comment]
Sendika, baris icin akademisyenler grubu falan da var. Onlar o kadar beceremeyebilir.

**Comment by rebasar** [comment]
Google Forms?

**Comment by csenol** [comment]
duplicate #5
