### ISSUE TITLE
Yansımalar

### ISSUE THREAD

**Issue by ekinertac** [chrishoca/chrishoca.github.com#26]
Yansımalar sayfasında verilen linklere havuz medyasından da linkler eklenebilir, özellikle ingilizce havuz medyasından. 

Olay "İngiliz Akedemisyen" den, "İngiliz Ajan" a dönmüş durumda

**Comment by csenol** [comment]
Neden yapalim bunu ? Bir de ornek link verebilir misin ?

**Comment by csenol** [comment]
cevab veremedi. kapiyorum
