### ISSUE TITLE
isim listesine dinamik eklenme ozelligi

### ISSUE THREAD

**Issue by coskung** [chrishoca/chrishoca.github.com#5]
Vatandas gelip kolayca ismini oraya ekleyebilsin

**Comment by rebasar** [comment]
Formu yaptık ama listeye otomatik ekleme olsa daha iyi olacak tabi ki

**Comment by yyalim** [comment]
Statik HTML ile mümkün değil ama Firebase benzeri biryere veri gönderip, çekilerek yapılabilir.

**Comment by rebasar** [comment]
Aramizdaki bir takim developerlar Rails olsun, Django olsun bence biraz ugrasip birkac saatte bunun icin birseyler yazabilirler.

**Comment by csenol** [comment]
Change.org a yuruduk. Kapiyorum
